# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Shared configuration for all resources, more in
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary"

Parameters:
  AppId:
    Type: String
  Purpose:
    Type: String
    Default: develop
    AllowedValues:
      - develop
      - production
    Description: The purpose of this instance.
  AirtableBase:
    Type: String
  AirtableApiKey:
    Type: String
    NoEcho: true
  AirtableCandidatesTable:
    Type: String
  AirtableMessagesTable:
    Type: String
  TwilioAccountSid:
    Type: String
    NoEcho: true
  TwilioAuthToken:
    Type: String
    NoEcho: true
  TwilioPhone:
    Type: String
  CrossknowledgeHost:
    Type: String
  CrossknowledgeApiKey:
    Type: String
    NoEcho: true
  ErrorTopicArn:
    Type: String
    # Default: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:LambdaError"
  DefaultLayerArn:
    Type: String
    Default: arn:aws:lambda:eu-west-3:452969718563:layer:konexio-backend-dependencies:132

Conditions:
  IsProduction: !Equals [!Ref Purpose, production]
  IsNotProduction: !Not [Condition: IsProduction]

# Global information for all the functions
Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 3
    Tracing: Active
    CodeUri: src/

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: put-twilio-messages-into-airtable.js

  #
  # FUNCTIONS
  #
  # On créé à chaque fois 2 fonction pour chacun des env pour ne pas mélanger les variable denv
  putTwilioMessagesIntoAirtable:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "putTwilioMessagesIntoAirtable_${Purpose}"
      Description: "Récupère toutes les 15 minutes les derniers SMS reçus et les envoies à Airtable."
      Handler: handlers/put-twilio-messages-into-airtable.putTwilioMessagesIntoAirtable
      Timeout: 20
      CodeUri: src/
      Layers:
        - !Ref KonexioBackendDepLayer
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: '*'
      Environment:
        Variables:
          AIRTABLE_BASE: !Ref AirtableBase
          AIRTABLE_API_KEY: !Ref AirtableApiKey
          AIRTABLE_CANDIDATES_TABLE: !Ref AirtableCandidatesTable
          AIRTABLE_MESSAGE_TABLE: !Ref AirtableMessagesTable
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE: !Ref TwilioPhone
          # CROSSKNOWLEDGE_HOST: !Ref CrossknowledgeHost
          # CROSSKNOWLEDGE_API_KEY: !Ref CrossknowledgeApiKey
          ERROR_TOPIC_ARN: !Ref ErrorTopicArn
          PURPOSE: !Ref Purpose

  # This is a Lambda function config associated with the source code: create-crossknowledge-learners.js
  createCrossknowledgeLearners:
    Type: AWS::Serverless::Function
    Condition: IsNotProduction
    Properties:
      FunctionName: !Sub "createCrossknowledgeLearners_${Purpose}"
      Description: "Créé des comptes apprenants dans crossknowledge."
      Handler: handlers/create-crossknowledge-learners.createCrossknowledgeLearners
      CodeUri: src/
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [IsProduction, Linear10PercentEvery1Minute, AllAtOnce]
      Layers:
        - !Ref KonexioBackendDepLayer
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /crossknowledge/learners
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
      Environment:
        Variables:
          # AIRTABLE_BASE: !Ref AirtableBase
          # AIRTABLE_API_KEY: !Ref AirtableApiKey
          # AIRTABLE_CANDIDATES_TABLE: !Ref AirtableCandidatesTable
          # AIRTABLE_MESSAGE_TABLE: !Ref AirtableMessagesTable
          # TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          # TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          # TWILIO_PHONE: !Ref TwilioPhone
          CROSSKNOWLEDGE_HOST: !Ref CrossknowledgeHost
          CROSSKNOWLEDGE_API_KEY: !Ref CrossknowledgeApiKey
          ERROR_TOPIC_ARN: !Ref ErrorTopicArn
          PURPOSE: !Ref Purpose

  # This is a Lambda function config associated with the source code: create-crossknowledge-sessions.js
  createCrossknowledgeSessions:
    Type: AWS::Serverless::Function
    Condition: IsNotProduction
    Properties:
      FunctionName: !Sub "createCrossknowledgeSessions_${Purpose}"
      Description: "Créé des sessions dans crossknowledge et les lie à des apprenants."
      Timeout: 30
      Handler: handlers/create-crossknowledge-sessions.createCrossknowledgeSessions
      CodeUri: src/
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [IsProduction, Linear10PercentEvery1Minute, AllAtOnce]
      Layers:
        - !Ref KonexioBackendDepLayer
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /crossknowledge/sessions
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
      Environment:
        Variables:
          # AIRTABLE_BASE: !Ref AirtableBase
          # AIRTABLE_API_KEY: !Ref AirtableApiKey
          # AIRTABLE_CANDIDATES_TABLE: !Ref AirtableCandidatesTable
          # AIRTABLE_MESSAGE_TABLE: !Ref AirtableMessagesTable
          # TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          # TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          # TWILIO_PHONE: !Ref TwilioPhone
          CROSSKNOWLEDGE_HOST: !Ref CrossknowledgeHost
          CROSSKNOWLEDGE_API_KEY: !Ref CrossknowledgeApiKey
          ERROR_TOPIC_ARN: !Ref ErrorTopicArn
          PURPOSE: !Ref Purpose

 #
 # VERSIONS
 #
  putTwilioMessagesIntoAirtableVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref putTwilioMessagesIntoAirtable
      Description: Version déployé automatiquement
  putTwilioMessagesIntoAirtableAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref putTwilioMessagesIntoAirtable
      FunctionVersion: !GetAtt putTwilioMessagesIntoAirtableVersion.Version
      Name: Staging

 #
 # EVENTS
 #
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "Schedule15minutes_${Purpose}"
      Description: Déclenché toutes les 15 minutes
      ScheduleExpression: "rate(15 minutes)"
      State: !If [IsProduction, "ENABLED", "DISABLED"]
      Targets: 
        - Arn: !Ref putTwilioMessagesIntoAirtableAlias
          Id: putTwilioMessagesIntoAirtableAlias
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref putTwilioMessagesIntoAirtableAlias
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Purpose
      TracingEnabled: true
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
      Cors:
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowOrigin: "'*'"

  #
  # OTHERS
  #
  KonexioBackendDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: konexio-backend-dependencies
      Description: Dependencies for konexio-backend
      ContentUri: lib/
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
        - nodejs10.x
        - nodejs12.x
      LicenseInfo: "MIT"
      RetentionPolicy: Delete

  # fonction fantoche permettant de laisser passer mon api gateway en prod sans route concrete
  testprod:
    Type: AWS::Serverless::Function
    Condition: IsProduction
    Properties:
      FunctionName: !Sub "testprod_${Purpose}"
      Description: "Accompagne l'apigateway pour la production."
      Handler: handlers/create-crossknowledge-sessions.createCrossknowledgeSessions
      CodeUri: src/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /testprod
            RestApiId: !Ref ApiGateway
            Auth:
              ApiKeyRequired: true
